# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_int <- function(n) {
    .Call('_RCPPbart_sample_int', PACKAGE = 'RCPPbart', n)
}

sample_double <- function(vec) {
    .Call('_RCPPbart_sample_double', PACKAGE = 'RCPPbart', vec)
}

sample_rule <- function(x_cut_var, x_obs_var, node_min_size) {
    .Call('_RCPPbart_sample_rule', PACKAGE = 'RCPPbart', x_cut_var, x_obs_var, node_min_size)
}

node_loglikelihood_r <- function(residuals, node_index, tau, tau_mu) {
    .Call('_RCPPbart_node_loglikelihood_r', PACKAGE = 'RCPPbart', residuals, node_index, tau, tau_mu)
}

dhcauchy <- function(x, location, sigma) {
    .Call('_RCPPbart_dhcauchy', PACKAGE = 'RCPPbart', x, location, sigma)
}

bart <- function(x_train, y, x_test, xcut, n_tree, n_mcmc, n_burn, n_min_size, tau, mu, tau_mu, naive_sigma, alpha, beta, a_tau, d_tau) {
    .Call('_RCPPbart_bart', PACKAGE = 'RCPPbart', x_train, y, x_test, xcut, n_tree, n_mcmc, n_burn, n_min_size, tau, mu, tau_mu, naive_sigma, alpha, beta, a_tau, d_tau)
}

bolean_test <- function(x, y) {
    .Call('_RCPPbart_bolean_test', PACKAGE = 'RCPPbart', x, y)
}

new_vec <- function(old_vec) {
    .Call('_RCPPbart_new_vec', PACKAGE = 'RCPPbart', old_vec)
}

filling_vec <- function(x) {
    .Call('_RCPPbart_filling_vec', PACKAGE = 'RCPPbart', x)
}

